name: webview_flutter_jsbridge
description: 'A flutter jsbridge package compatible with webview_flutter 4.0.0, dependent on inject javascript.'
version: 0.1.0
environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
